name: Builder

on:
  repository_dispatch:
    types: [Builder]

  workflow_dispatch:
    inputs:
      parameter1:
        description: 'parameter1'     
        required: true
        default: ${{ github.event.client_payload.parameter1 }}
      parameter2:
        description: 'parameter2'     
        required: true
        default: ${{ github.event.client_payload.parameter2 }}
      parameter3:
        description: 'parameter3'     
        required: true
        default: ${{ github.event.client_payload.parameter3 }}

env:
  PARAM1: ${{ github.event.inputs.parameter1 }}
  PARAM2: ${{ github.event.inputs.parameter2 }}
  PARAM3: ${{ github.event.inputs.parameter3 }}

jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Parameter Information
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
          echo "Parameter 3: $PARAM3"

  Tester:
    runs-on: ubuntu-latest
    needs: Builder
    steps:
      - name: Parameter Information
        run: |
          echo "Parameter 1: $PARAM1"
          echo "Parameter 2: $PARAM2"
          echo "Parameter 3: $PARAM3"
