name: Repository Dispatch Trigger

on:
  workflow_dispatch:

jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: workflow-dispatcher
      uses: ./.github/actions/workflow-dispatcher
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event_type: Builder
        input: '{ "parameter1": "Value1", "parameter2": "Value2", "parameter3": "Value3" }'
        wait_time: 5
        max_time: 180
