name: workflow_dispatch Trigger

on:
  workflow_dispatch:

jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Your Service
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: n-stone
          repo: test
          github_token: ${{ secrets.ACCESS_TOKEN }}
          workflow_file_name: builder.yml
          wait_interval: 10
          client_payload: '{ "parameter1": "value1", "parameter2": "value2", "parameter3": "value3" }'
          propagate_failure: true
          trigger_workflow: true
          wait_workflow: true
